### ISSUE TITLE
Low Prio: A Client-Generated id

### ISSUE THREAD

**Issue by Nizari** [cloudcreativity/laravel-json-api#157] opened 2018-04-03 06:04 UTC
Based on http://jsonapi.org/format/#crud-creating-client-ids:

_A server MAY accept a client-generated ID along with a request to create a resource. An ID MUST be specified with an id key, the value of which MUST be a universally unique identifier.
...
A server MUST return 403 Forbidden in response to an unsupported request to create a resource with a client-generated ID.
...
A server MUST return 409 Conflict when processing a POST request to create a resource with a client-generated ID that already exists._

Now the id parameter is just ignored so it works fine. Would be a nice feature to add for after verison 1.0.

**Comment by danherd** [comment] 2018-04-10 11:18
Isn't this a duplicate of #85?

**Comment by lindyhopchris** [comment] 2018-04-10 12:56
Yep, it is a bit of a duplicate. Leaving both open at the moment and I'll get them closed when I move on to validation updates. I've got a `1.0.0-alpha.1` release coming very soon and will be sorting out several of the validation issues (including client generated ids) in one of the subsequent alpha releases.

**Closed** 2018-10-11 15:55 UTC
Labels: enhancement
