### ISSUE TITLE
Relationship's required rule is not working properly

### ISSUE THREAD

**Issue by GSpecDrum** [cloudcreativity/laravel-json-api#515] opened 2020-06-07 15:44 UTC
Hello everyone!

As shown here, https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#modify-resource-validation your package will check that request has "relationships" part of "data" object with correct relationship object, if I set rules in way, provided in the docs:
```
use CloudCreativity\LaravelJsonApi\Rules\HasMany;
use CloudCreativity\LaravelJsonApi\Rules\HasOne;
use CloudCreativity\LaravelJsonApi\Validation\AbstractValidators;

class Validators extends AbstractValidators
{
    // ...

    protected function rules($record = null): array
    {
        return [
            'title' => 'required|string|min:1|max:255',
            'content' => 'required|string|min:1',
            "another-field" => 'string|unique:posts,another_field',
            'author' => [
                'required',
                new HasOne('users'),
            ],
            'tags' => new HasMany('tags'),
        ];
    }
}
```
But your package will not throw the validation exception, and will try to create new model, if I send request like this:
```
POST /api/posts HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type": "posts",
        "attributes": {
            "title": "Hello World",
            "content": "...",
            "author": {
                "data": {
                    "type": "users",
                    "id": "123"
                }
            },
            "another-field": "..."
        }
    }
}
```
Relationship's 'required' rule passes, but document doesn't have "relationship" structure at all.

**Comment by lindyhopchris** [comment] 2020-06-14 15:13
Hi,

Thanks for reporting this; I hadn't thought of this scenario (sending a relationship object as an attribute), and yeah, the validator will not pick up on this at the moment.

The problem is that people wanted shorter rule names, i.e. being able to just define a rule for `author`, rather than having to specify `data.relationships.author`, `data.attributes.title` etc which would get very verbose. So the solution was based on the JSON API rule that attributes and relationships are collectively field names, and to use field names for the validation rules.

However the unfortunate side of this is that the validation rules cannot therefore tell whether they are an attribute or a relationship as they are dealt with collectively as fields.

We might have to switch back to the verbose form of always using `data.attributes` and `data.relationships` prefixes in future versions.

**Comment by lindyhopchris** [comment] 2021-02-05 12:50
Closing this as it is solved in the new `laravel-json-api/laravel` package. See https://laraveljsonapi.io

**Closed by lindyhopchris** 2021-02-05 12:50 UTC
