### ISSUE TITLE
Eloquent adapter should pass attributes to newInstance() in createRecord()

### ISSUE THREAD

**Issue by k8n** [cloudcreativity/laravel-json-api#350] opened 2019-04-19 01:24 UTC
https://github.com/cloudcreativity/laravel-json-api/blob/72f80003142a7dd89506a012290457a4b19cd23e/src/Eloquent/AbstractAdapter.php#L287

Should probably return:
```php
return $this->model->newInstance($resource->getAttributes()->toArray());
```

`newInstance` constructor may need the attributes to create the right model. Case in point - [tightenco/parental](https://github.com/tightenco/parental), which needs the attributes to create the right model in the inheritance tree:

https://github.com/tightenco/parental/blob/0ca75a7782ce784b12630ba77efb18cf1f118298/src/HasChildren.php#L52

**Comment by lindyhopchris** [comment] 2019-04-19 06:41
Hi! The problem is that `$resource->getAttributes()` gives you the JSON API attributes - not the model attributes. While they may be the same in some implementations, they are not the same in all instances. Which is why we have to loop through them and normalize them when we're filling the record:
https://github.com/cloudcreativity/laravel-json-api/blob/72f80003142a7dd89506a012290457a4b19cd23e/src/Eloquent/Concerns/DeserializesAttributes.php#L104-L113

The `createRecord` is there so that the developer can overload it if they need to do something different when creating a new instance - so I'd suggest for the package that you mention you might need to overload it and use whatever attributes you need to create the new model instance.

**Comment by lindyhopchris** [comment] 2019-06-05 16:11
Closing this due to lack of reply... feel free to re-open if needed.

FYI the solution here is to overload the `createRecord()` method.

**Closed by lindyhopchris** 2019-06-05 16:11 UTC
Labels: question

**Comment by k8n** [comment] 2019-06-05 22:53
Thank you for the analysis.

In the end, I went KISS and ditched model inheritance in my app.
