### ISSUE TITLE
Question: how do I camelCase my resource types?

### ISSUE THREAD

**Issue by faraoban** [cloudcreativity/laravel-json-api#224] opened 2018-09-11 09:51 UTC
If I try to name my resource type like `endUsers` or `managementUsers`, I get a 404 on the associated endpoint (/api/v1/endUsers). However, if I name the resource type `endusers` / `end-users` / `end_users`, the endpoint returns the right data.

Edit: clarify

**Comment by lindyhopchris** [comment] 2018-09-11 09:55
Hi! That is a very good question as I've never tried it before. It should obviously work but as I've never tried it I don't know for sure. I'll take a look at adding in tests to ensure it works and hopefully flush out whatever bug you've found.

**Comment by faraoban** [comment] 2018-09-11 11:12
Ah perfect, I'll create a pull request if I find a solution anytime soon.

**Comment by faraoban** [comment] 2018-09-11 11:14
Maybe I should add that we use different `ResourceProvider`s as we are developing Laravel packages that use this package.

**Comment by faraoban** [comment] 2018-09-11 11:41
It certainly has something to do with the `groupAction()` method in the `ResourceGroup` class, where the 'prefix' string is dasherized using the `Str::dasherize()` method. Removing it doesn't resolve the issue though. We'll use dasherized endpoints for now.

**Comment by lindyhopchris** [comment] 2018-09-20 16:36
@faraoban as far as i can tell removing the dasherize from within the resource group solves this. The integration test in the above commit was failing before i changed that line and passes after.

I think this should now work but if you were able to confirm it's working for you that would help.

**Comment by lindyhopchris** [comment] 2018-10-11 16:21
@faraoban have closed this as I hadn't heard back from you. As far as I'm aware the problem is fixed. If not, please re-open the issue.

**Closed** 2018-10-11 16:20 UTC
Labels: bug
