### ISSUE TITLE
How to include relationship data ?

### ISSUE THREAD

**Issue by lilouch** [cloudcreativity/laravel-json-api#527] opened 2020-07-14 08:58 UTC
I'm fetching users and my response so far is the following :

```
    type: "users",
    id: "1",
    attributes: {
    name: "myname",
    email: "name@domain",
    },
    relationships: {
       roles: {
          data: [
            {
              type: "roles",
              id: "9"
            }
          ],
          links: {
            self: "http://127.0.0.1:8000/api/v1/users/1/relationships/roles",
            related: "http://127.0.0.1:8000/api/v1/users/1/roles"
            }
          }
          },
          links: {
            self: "http://127.0.0.1:8000/api/v1/users/1"
          }
      },
```

How is it possible to include in my relationship data, the attribute ?
Like

```
  roles: {
          data: [
            {
              type: "roles",
              id: "9"
              name : "Admin"
            }
          ],
```
I'm not sure, I saw that info on the doc if it's possible to do that or not.

Thank in advance

**Comment by ben221199** [comment] 2020-07-15 12:00
Duplicate of #523

**Comment by lindyhopchris** [comment] 2020-07-15 15:39
Closing, see https://github.com/cloudcreativity/laravel-json-api/issues/523#issuecomment-658840713

**Closed by lindyhopchris** 2020-07-15 15:39 UTC
