### ISSUE TITLE
Toggling between JsonApi and Laravel Exceptions

### ISSUE THREAD

**Issue by JeanLucEsser** [cloudcreativity/laravel-json-api#286] opened 2019-01-25 16:39 UTC
Hi there,

I'm curious about the way you handle Exceptions in development so that:

- they are not catched by JsonApi (without commenting the Handler each and every time)
- they are not formatted as Json even if Accept JSON is defined in header

The key here is to easily be able to toggle between all options, as in development you might want to check if the error is correctly catched and displayed in JsonApi as well as rendering the full error in a Laravel way for full debugging purposes.

Did I miss something obvious?

Thanx

**Comment by lindyhopchris** [comment] 2019-01-25 17:09
So I do test-driven development: so I'm effectively using PHPUnit for API development. So I don't tend to use HTML responses for development. When I'm actually firing API requests against an application I use a client so I want JSON in the response and use the application log for exception traces. If I encountered an error I'd actually reproduce it in a PHPUnit test before debugging it, so again not reliant on HTML for debugging.

This is all totally personal preference though! You're right that this package should maybe provide a way of skipping the JSON API rendering of exceptions if that's the developer's preference.

How would you like it implemented? Best you and others give me your views as I won't actually be using it!

**Comment by lindyhopchris** [comment] 2019-01-25 17:13
Of course you can set this up yourself. The installation guide says to do this in your handler:

```php
    public function render($request, Exception $e)
    {
      if ($this->isJsonApi($request, $e)) {
        return $this->renderJsonApi($request, $e);
      }

      // do standard exception rendering here...
    }
```

But of course you could do:

```php
    public function render($request, Exception $e)
    {
      if (!app()->environment('local') && $this->isJsonApi($request, $e)) {
        return $this->renderJsonApi($request, $e);
      }

      // do standard exception rendering here...
    }
```

For the JSON responses it's Laravel doing that, not this package so out of scope of this package really.

**Comment by lindyhopchris** [comment] 2019-04-12 14:50
I'm going to close this because the question was answered... feel free to re-open or open a different issue if you think there's anything else to answer!

**Closed by lindyhopchris** 2019-04-12 14:50 UTC
Labels: question
